apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-frontend
spec:
  selector:
    matchLabels:
      app: user-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
      - name: user-frontend
        image: user-frontend:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-frontend-service
spec:
  type: NodePort
  selector:
    app: user-frontend
  ports:
    - name: user-frontend
      protocol: TCP
      port: 80
      targetPort: 80